export const CONFIG = Object.freeze({
  TILE_SIZE: 32,
  CANVAS_WIDTH: 1280,
  CANVAS_HEIGHT: 720,
  FIXED_TIMESTEP: 1 / 60,
  MAX_FRAME_TIME: 0.25,
  MAX_CATCH_UP_STEPS: 8,
  DEVELOPMENT_MODE: true,
  GRAVITY: 1500,
  WATER_GRAVITY: 360,
  MOVE_ACCELERATION: 3400,
  WATER_ACCELERATION: 1200,
  MAX_RUN_SPEED: 260,
  MAX_SWIM_SPEED: 165,
  GROUND_FRICTION: 2600,
  AIR_DRAG: 260,
  WATER_DRAG: 700,
  JUMP_FORCE: 530,
  JUMP_CUT_MULTIPLIER: 0.45,
  JUMP_APEX_GRAVITY_MULTIPLIER: 0.78,
  FALL_GRAVITY_MULTIPLIER: 1.18,
  SWIM_FORCE: 360,
  PLAYER_WIDTH: 28,
  PLAYER_HEIGHT: 58,
  PLAYER_SPRITE_WIDTH: 64,
  PLAYER_SPRITE_HEIGHT: 96,
  PLAYER_COYOTE_SECONDS: 0.12,
  PLAYER_JUMP_BUFFER_SECONDS: 0.14,
  PLAYER_MAX_FALL_SPEED: 980,
  PLAYER_MAX_RISE_SPEED: 620,
  PLAYER_ACTION_SECONDS: 0.42,
  PRIMARY_CLICK_FEEDBACK_SECONDS: 0.36,
  PLAYER_INTERACTION_RANGE_TILES: 3.5,
  TERRAIN_DIG_RANGE_TILES: 4,
  MAX_HEALTH: 100,
  MAX_OXYGEN: 100,
  OXYGEN_DRAIN_PER_SECOND: 12,
  OXYGEN_REFILL_PER_SECOND: 24,
  DROWN_DAMAGE_PER_SECOND: 8,
  FALL_DAMAGE_THRESHOLD: 760,
  FIRST_ENCOUNTER_DELAY_SECONDS: 15,
  ENCOUNTER_INTERVAL_SECONDS: 60,
  ENCOUNTER_RESPONSE_SECONDS: 20,
  DEV_FIRST_ENCOUNTER_DELAY_SECONDS: 6,
  DEV_ENCOUNTER_INTERVAL_SECONDS: 18,
  INVENTORY_SIZE: 24,
  HOTBAR_SIZE: 9,
  RAFT_MAX_WIDTH: 30,
  RAFT_MAX_HEIGHT: 12,
  RAFT_EXTENTS: { minX: -15, maxX: 14, minY: -8, maxY: 3 },
  RAFT_BLOCK_STACK_LIMIT: 3,
  RAFT_WATERLINE_TILE_OFFSET: -1,
  RAFT_SUBMERGED_TILES: 0.5,
  GENERATION_VERSION: 4,
  ISLAND_HEIGHT: 48,
  ISLAND_DIMENSIONS: {
    small: { width: 192, height: 96, seaLevelTile: 30 },
    medium: { width: 256, height: 112, seaLevelTile: 32 },
    large: { width: 320, height: 128, seaLevelTile: 34 }
  },
  GENERATION_MAX_ATTEMPTS: 12,
  ISLAND_WIDTHS: {
    small: 170,
    medium: 220,
    large: 270
  },
  SEA_LEVEL_TILE: 26,
  AUTOSAVE_SECONDS: 20,
  SAVE_KEY: "raftbound.save.v1",
  INVALID_SAVE_KEY: "raftbound.invalid-save",
  BASIC_RESOURCE_DEATH_DROP_PERCENT: 0.25
});

export function encounterDelay() {
  return CONFIG.DEVELOPMENT_MODE
    ? CONFIG.DEV_FIRST_ENCOUNTER_DELAY_SECONDS
    : CONFIG.FIRST_ENCOUNTER_DELAY_SECONDS;
}

export function encounterInterval() {
  return CONFIG.DEVELOPMENT_MODE
    ? CONFIG.DEV_ENCOUNTER_INTERVAL_SECONDS
    : CONFIG.ENCOUNTER_INTERVAL_SECONDS;
}
